-- Robust fix for RLS policies on users and app_user_mappings tables
-- This migration is idempotent and can be run multiple times safely
--
-- Root cause: The original schema enabled RLS on users table but had no INSERT policy
-- The INSERT was blocked because RLS denies by default
--
-- This fix uses auth.uid() IS NOT NULL which is more reliable than auth.role() = 'authenticated'

-- ============================================================
-- USERS TABLE - Fix INSERT policy
-- ============================================================

-- Drop potentially broken policies
DROP POLICY IF EXISTS "Users can view own data" ON users;
DROP POLICY IF EXISTS "Authenticated users can create users" ON users;
DROP POLICY IF EXISTS "Users can view own data via mapping" ON users;
DROP POLICY IF EXISTS "Users can update own data via mapping" ON users;
DROP POLICY IF EXISTS "Users can delete own data via mapping" ON users;

-- Allow any authenticated user to INSERT a new user record
-- This is safe because user_id is generated by the database, not user-controlled
CREATE POLICY "Authenticated users can insert users" ON users
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Allow users to SELECT their own user records via app_user_mappings
CREATE POLICY "Users can view own data via mapping" ON users
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = users.id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

-- Allow users to UPDATE their own user records via app_user_mappings
CREATE POLICY "Users can update own data via mapping" ON users
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = users.id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

-- Allow users to DELETE their own user records via app_user_mappings
CREATE POLICY "Users can delete own data via mapping" ON users
  FOR DELETE USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = users.id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- APP_USER_MAPPINGS TABLE - Ensure policies exist
-- ============================================================

-- Drop and recreate to ensure correct policies
DROP POLICY IF EXISTS "Users can view own app mappings" ON app_user_mappings;
DROP POLICY IF EXISTS "Users can insert own app mappings" ON app_user_mappings;

-- Allow users to view their own mappings
CREATE POLICY "Users can view own app mappings" ON app_user_mappings
  FOR SELECT USING (auth.uid() = auth_user_id);

-- Allow users to create mappings for themselves
CREATE POLICY "Users can insert own app mappings" ON app_user_mappings
  FOR INSERT WITH CHECK (auth.uid() = auth_user_id);

-- ============================================================
-- USER_SHAPES TABLE - Fix policies
-- ============================================================

DROP POLICY IF EXISTS "Users can view own shapes" ON user_shapes;
DROP POLICY IF EXISTS "Users can insert own shapes" ON user_shapes;
DROP POLICY IF EXISTS "Users can update own shapes" ON user_shapes;
DROP POLICY IF EXISTS "Users can view own shapes via mapping" ON user_shapes;
DROP POLICY IF EXISTS "Users can insert own shapes via mapping" ON user_shapes;
DROP POLICY IF EXISTS "Users can update own shapes via mapping" ON user_shapes;

CREATE POLICY "Users can view own shapes via mapping" ON user_shapes
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = user_shapes.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own shapes via mapping" ON user_shapes
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = user_shapes.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own shapes via mapping" ON user_shapes
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = user_shapes.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- RATINGS TABLE - Fix policies
-- ============================================================

DROP POLICY IF EXISTS "Users can view own ratings" ON ratings;
DROP POLICY IF EXISTS "Users can insert own ratings" ON ratings;
DROP POLICY IF EXISTS "Users can view own ratings via mapping" ON ratings;
DROP POLICY IF EXISTS "Users can insert own ratings via mapping" ON ratings;

CREATE POLICY "Users can view own ratings via mapping" ON ratings
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = ratings.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own ratings via mapping" ON ratings
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = ratings.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- PREDICTIONS TABLE - Fix policies
-- ============================================================

DROP POLICY IF EXISTS "Users can view own predictions" ON predictions;
DROP POLICY IF EXISTS "Users can insert own predictions" ON predictions;
DROP POLICY IF EXISTS "Users can update own predictions" ON predictions;
DROP POLICY IF EXISTS "Users can view own predictions via mapping" ON predictions;
DROP POLICY IF EXISTS "Users can insert own predictions via mapping" ON predictions;
DROP POLICY IF EXISTS "Users can update own predictions via mapping" ON predictions;

CREATE POLICY "Users can view own predictions via mapping" ON predictions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = predictions.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own predictions via mapping" ON predictions
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = predictions.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own predictions via mapping" ON predictions
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = predictions.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

-- ============================================================
-- USER_PROFILES TABLE - Fix policies
-- ============================================================

DROP POLICY IF EXISTS "Users can view own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users can view own profile via mapping" ON user_profiles;
DROP POLICY IF EXISTS "Users can insert own profile via mapping" ON user_profiles;
DROP POLICY IF EXISTS "Users can update own profile via mapping" ON user_profiles;

CREATE POLICY "Users can view own profile via mapping" ON user_profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = user_profiles.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert own profile via mapping" ON user_profiles
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = user_profiles.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update own profile via mapping" ON user_profiles
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM app_user_mappings
      WHERE app_user_mappings.user_id = user_profiles.user_id
        AND app_user_mappings.auth_user_id = auth.uid()
    )
  );
